linters:
  NestingDepth:
    enabled: true
    max_depth: 4
    ignore_parent_selectors: false

  PropertySortOrder:
    enabled: false

  SelectorDepth:
      enabled: true
      max_depth: 4

  LeadingZero:
      enabled: true
      style: include_zero
