name: Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Nodejs ${{ matrix.node }}
        uses: actions/setup-node@v1
      - name: Install dependencies
        env:
          CI: true
        run: npm install
      - name: Build the plugin
        run: npm run build
      - name: Deploy the plugin
        if: success()
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          FORMBUILDER_WEBSITE_DIR: ${{ secrets.FORMBUILDER_WEBSITE_DIR }}
          FORMBUILDER_WEBSITE_REPO: ${{ secrets.FORMBUILDER_WEBSITE_REPO }}
        run: |
          echo "https://${GH_TOKEN}:@github.com" > .git/credentials
          git config --global credential.helper "store --file=.git/credentials"
          git config --local user.email "kevin.b.chappell@gmail.com"
          git config --local user.name "Kevin Chappell"
          git clone --depth 1 $FORMBUILDER_WEBSITE_REPO $FORMBUILDER_WEBSITE_DIR 2> /dev/null
          npm run deploy:all
